### ISSUE TITLE
Add a summary for: What Is CORS

### ISSUE THREAD

**Issue by segunolalive** [segunolalive/frontend-weekly#49]
Add a summary for [What Is CORS](https://frontendweekly.dev/sessions/what-is-cors).

## Note
- We prefer video summaries to be 2 or 3 paragraphs long. Summaries could be longer if absolutely necessary. You should add a bullet list of things the viewer will learn at the end.
- Summaries should be written in markdown.
- Summaries should be saved in the `src/session-summaries` folder.
- Summary files should be named with the session slug e.g The slug for the [Design Systems Part 2](https://frontendweekly.dev/sessions/design-systems-part-2) video is `design-systems-part-2`, so the summary file for that session should be named `design-systems-part-2.md`.
- Select the `Session Summary PR Template` when making a Pull Request.

**Comment by Chimdiya1** [comment]
Hi, @segunolalive I would like to work on this but I can't figure out how to assign myself here on Github.

**Comment by segunolalive** [comment]
I just assigned you to this issue.

On the right side of the page, you should see `assignees`. You can assign to yourself from there

**Comment by segunolalive** [comment]
When creating your PR.

Add this to the bottom of the Pull Request: `fixes: #49`
That would automatically close this issue when your PR is merged.
