### ISSUE TITLE
Add a Code of Conduct

### ISSUE THREAD

**Issue by segunolalive** [segunolalive/frontend-weekly#52]

**Comment by EmmanuelTheCoder** [comment]
Please provide a abuse reporting email for the code of conduct

**Comment by segunolalive** [comment]
At the moment, I'm unwilling to add another surface area to monitor, so I'd prefer all instances of inappropriate behaviour to be called out on Github.

If/when someone exhibits unacceptable behaviour, let it be pointed out right there and then. I believe this could be a good way to signal what is acceptable or not.
